### ISSUE TITLE
Can't import "YAML" module

### ISSUE THREAD

**Issue by josai** [tifgan/stftGAN#3]
Not sure if this is specific to my machine or enviroment, but for some reason I can't import YAML despite installing it in conda. I also tried installing it in the local directory and no luck.

**Comment by nperraud** [comment]
Did you try to launch a python console and import YAML?

**Comment by andimarafioti** [comment]
I'm closing this since it's been inactive and it doesn't look like there is something we can do to fix the issue.

**Comment by andimarafioti** [comment]
Btw, `pip install pyyaml` solves this issue, but pyyaml was already the default in the requirements
