### ISSUE TITLE
missing test_spectrograms_and_derivs_1.mat file

### ISSUE THREAD

**Issue by josai** [tifgan/stftGAN#4]
Traceback (most recent call last):
  File "64md_8k.py", line 26, in <module>
    raw_data = scipy.io.loadmat(mat_path)
  File "C:\Users\The Atomizer\Miniconda3\envs\music2\lib\site-packages\scipy\io\matlab\mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Users\The Atomizer\Miniconda3\envs\music2\lib\site-packages\scipy\io\matlab\mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "C:\Users\The Atomizer\Miniconda3\envs\music2\lib\site-packages\scipy\io\matlab\mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '../../data/test_spectrograms_and_derivs_1.mat'

**Comment by nperraud** [comment]
Hi Josai,

Did you download the dataset? And extract the archives into the folder data?

**Comment by josai** [comment]
Seemed to work.

**Comment by josai** [comment]
nvm... still not working. Downloaded the datasets and I still have the same error.

That file does not exist.

**Comment by nperraud** [comment]
@andimarafioti is it possible to make a download script that will download and extract the data at the good place? I will send you one of mine that you can modify.

**Comment by andimarafioti** [comment]
Hey, on the readme it was not super clear, but besides downloading the datasets, you need to pre-process them and generate the time-frequency features we use for training. There is a notebook to do that with any files located at 'data/generate commands dataset.ipynb'. Now to stream line it and make it more clear, I added two scripts to the main folder that you can run to download the commands dataset and generate the files. These are: "download_commands.py" and "generate_commands_dataset.py". I also updated the readme to point to this new files. Hope this solves the issue.

**Comment by andimarafioti** [comment]
Closing the issue as I assumed it is solved.
